// Metadata for /post/[id] is generated by page.tsx (richer OG/Twitter + JSON-LD).
// This layout is a plain pass-through to avoid a duplicate generateMetadata.
export default function PostLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
