/**
 * Data export utilities — CSV, JSON, PDF
 */

// ── CSV ────────────────────────────────────────────────────

function escapeCsvValue(value: unknown): string {
  if (value == null) return ''
  const str = String(value)
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`
  }
  return str
}

export function exportToCSV(data: Record<string, unknown>[], filename: string): void {
  if (!data.length) return
  const keys = Object.keys(data[0])
  const header = keys.map(escapeCsvValue).join(',')
  const rows = data.map(row => keys.map(k => escapeCsvValue(row[k])).join(','))
  const csv = [header, ...rows].join('\n')
  downloadBlob(csv, `${filename}.csv`, 'text/csv;charset=utf-8;')
}

// ── JSON ───────────────────────────────────────────────────

export function exportToJSON(data: unknown, filename: string): void {
  const json = JSON.stringify(data, null, 2)
  downloadBlob(json, `${filename}.json`, 'application/json;charset=utf-8;')
}

// ── PDF via print ─────────────────────────────────────────────
// Opens a print dialog with a formatted HTML table. Users can "Save as PDF" from the dialog.

export function exportToPDF(data: Record<string, unknown>[], filename: string): void {
  if (!data.length) return

  const keys = Object.keys(data[0])
  const headerCells = keys.map(k =>
    `<th style="padding:8px 12px;text-align:left;font-size:11px;white-space:nowrap;color:#8b6fa8;text-transform:uppercase;letter-spacing:0.5px;border-bottom:2px solid #8b6fa8">${escapeHtml(k)}</th>`
  ).join('')
  const bodyRows = data.map((row, i) =>
    `<tr style="background:${i % 2 === 0 ? '#fff' : '#f9f7fc'}">${keys.map(k => {
      const val = String(row[k] ?? '')
      // Color positive/negative values
      const isNeg = val.startsWith('-')
      const isPct = val.endsWith('%')
      const color = isPct ? (isNeg ? '#ef4444' : val !== '0.00%' ? '#22c55e' : '#666') : '#333'
      return `<td style="padding:6px 12px;border-bottom:1px solid #eee;font-size:12px;color:${color};font-variant-numeric:tabular-nums">${escapeHtml(val)}</td>`
    }).join('')}</tr>`
  ).join('')

  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${escapeHtml(filename)}</title>
<style>
  @media print { body { margin: 0; } @page { size: landscape; margin: 10mm; } }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #222; }
  table { border-collapse: collapse; width: 100%; }
  .header { display: flex; justify-content: space-between; align-items: flex-end; border-bottom: 2px solid #8b6fa8; padding-bottom: 8px; margin-bottom: 16px; }
  .header h1 { font-size: 18px; color: #8b6fa8; margin: 0; font-weight: 800; }
  .header .meta { font-size: 10px; color: #999; text-align: right; }
  .footer { margin-top: 12px; font-size: 9px; color: #aaa; text-align: center; }
</style></head><body>
<div class="header">
  <h1>Arena Ranking — ${escapeHtml(filename.replace(/^arena-ranking-/, '').replace(/-/g, ' '))}</h1>
  <div class="meta">${escapeHtml(date)}<br/>arenafi.org</div>
</div>
<table><thead><tr>${headerCells}</tr></thead><tbody>${bodyRows}</tbody></table>
<div class="footer">${data.length} traders · Generated by Arena (arenafi.org)</div>
<script>window.onafterprint=function(){window.close()};window.print();<\/script>
</body></html>`

  const printWindow = window.open('', '_blank')
  if (printWindow) {
    printWindow.document.write(html)
    printWindow.document.close()
  }
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

// ── Blob download helper ───────────────────────────────────

function downloadBlob(content: string, filename: string, mimeType: string): void {
  const blob = new Blob(['\uFEFF' + content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// ── Data formatters ────────────────────────────────────────

/** @deprecated Use UnifiedTrader from '@/lib/types/unified-trader' for application code */
export interface TraderExportRow {
  rank: number
  handle: string
  source: string
  roi: string
  pnl: string
  win_rate: string
  max_drawdown: string
  arena_score: string
  trades_count: number
}

export function formatTraderData(traders: Array<Record<string, unknown>>): TraderExportRow[] {
  return traders.map((t, i) => ({
    rank: (t.rank as number) || i + 1,
    handle: String(t.handle || t.nickname || ''),
    source: String(t.source || ''),
    roi: fmtPct(t.roi),
    pnl: fmtNum(t.pnl),
    win_rate: fmtPct(t.win_rate),
    max_drawdown: fmtPct(t.max_drawdown),
    arena_score: fmtNum(t.arena_score),
    trades_count: Number(t.trades_count || 0),
  }))
}

export interface PortfolioExportRow {
  handle: string
  source: string
  allocation_pct: string
  risk_level: string
  expected_roi: string
  expected_drawdown: string
}

export function formatPortfolioData(portfolio: Array<Record<string, unknown>>): PortfolioExportRow[] {
  return portfolio.map(p => ({
    handle: String(p.handle || ''),
    source: String(p.source || ''),
    allocation_pct: fmtPct(p.allocation_pct),
    risk_level: String(p.risk_level || ''),
    expected_roi: fmtPct((p.expected_contribution as Record<string, unknown>)?.roi),
    expected_drawdown: fmtPct((p.expected_contribution as Record<string, unknown>)?.drawdown),
  }))
}

function fmtPct(v: unknown): string {
  if (v == null) return ''
  return `${Number(v).toFixed(2)}%`
}

function fmtNum(v: unknown): string {
  if (v == null) return ''
  return Number(v).toLocaleString('en-US', { maximumFractionDigits: 2 })
}
