#!/usr/bin/env bash
# Temporary local dev for manual quiz testing — no real Supabase required.
#
# Usage:
#   ./scripts/dev-quiz-local.sh
#
# Opens:
#   http://localhost:3000/quiz
#   http://localhost:3000/quiz/questions
#   http://localhost:3000/quiz/result?type=sniper&match=87

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env.local"

if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<'EOF'
# Auto-generated by scripts/dev-quiz-local.sh — quiz-only local dev (no real Supabase).
# Delete or replace with real credentials when working on other features.
NODE_ENV=development
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=https://placeholder.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=placeholder-anon-key
SUPABASE_URL=https://placeholder.supabase.co
SUPABASE_SERVICE_ROLE_KEY=placeholder-service-key
EOF
  echo "Created $ENV_FILE with quiz-only stub credentials."
else
  echo "Using existing $ENV_FILE"
fi

echo ""
echo "Quiz manual testing URLs:"
echo "  Start:    http://localhost:3000/quiz"
echo "  Questions http://localhost:3000/quiz/questions"
echo "  Result:   http://localhost:3000/quiz/result?type=sniper&match=87"
echo ""
echo "Note: recommended traders on the result page will be empty without real Supabase."
echo "      Start/questions/result UI and a11y changes still work for manual QA."
echo ""

exec env NODE_OPTIONS='--max-old-space-size=3584' npx next dev
